title: Oliver Bentham
url: "https://oliverbentham.com"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

footer: yes
footer_links:
- name: "email"
  link: "oliver.bentham (at) utah.edu"
- name: "Google Scholar"
  link: "https://scholar.google.com/citations?user=PdOTpqwAAAAJ&hl=en"
- name: "GitHub"
  link: "https://github.com/obentham"
- name: "Twitter"
  link: "https://twitter.com/obenthamo"
- name: "LinkedIn"
  link: "https://www.linkedin.com/in/oliverbentham/"
